version: "3"

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: leading
      POSTGRES_USER: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    command: -p 5432
